
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerSoapService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8090/booking?wsdl")
public class ServerSoapService
    extends Service
{

    private final static URL SERVERSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERSOAPSERVICE_EXCEPTION;
    private final static QName SERVERSOAPSERVICE_QNAME = new QName("http://server/", "ServerSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/booking?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERSOAPSERVICE_WSDL_LOCATION = url;
        SERVERSOAPSERVICE_EXCEPTION = e;
    }

    public ServerSoapService() {
        super(__getWsdlLocation(), SERVERSOAPSERVICE_QNAME);
    }

    public ServerSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERSOAPSERVICE_QNAME, features);
    }

    public ServerSoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVERSOAPSERVICE_QNAME);
    }

    public ServerSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERSOAPSERVICE_QNAME, features);
    }

    public ServerSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookingService
     */
    @WebEndpoint(name = "ServerSoapPort")
    public BookingService getServerSoapPort() {
        return super.getPort(new QName("http://server/", "ServerSoapPort"), BookingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookingService
     */
    @WebEndpoint(name = "ServerSoapPort")
    public BookingService getServerSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "ServerSoapPort"), BookingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERSOAPSERVICE_EXCEPTION!= null) {
            throw SERVERSOAPSERVICE_EXCEPTION;
        }
        return SERVERSOAPSERVICE_WSDL_LOCATION;
    }

}
